name: BaitMate OWASP Security Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐞 拉取正确镜像
        run: |
          docker pull owasp/zap-stable  # 注意镜像名称已移除 "2docker"
          docker tag owasp/zap-stable zap-image  # 添加镜像别名

      - name: 🕷️ 执行ZAP扫描
        uses: zaproxy/action-full-scan@v1.0.0  # 升级到最新版Action
        with:
          target: "http://47.129.5.86:8080"
          cmd_options: "-I -T 60"  # 增加超时设置
          rules_file_name: ".zap/rules.tsv"

      - name: 📤 上传报告
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Security-Report
          path: |
            zap_scan.log
            zap-report.html