name: OWASP ZAP Security Scan

on: [push, pull_request]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 防止CI阻塞

    steps:
      - name: 🛠️ Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 确保包含.zap配置目录
          fetch-depth: 0

      - name: 🎯 Health Check
        uses: wei/curl@v1.7
        with:
          args: -X HEAD --retry 3 --retry-delay 10 http://47.129.5.86:8080

      - name: 🔍 Full Security Scan
        uses: zaproxy/action-full-scan@v1.6.0  # Marketplace官方认证
        with:
          target: 'http://47.129.5.86:8080'
          format: 'html'  # 支持html/json/md三种格式
          rules: 'media/conf/zap/rules.tsv'  # 自定义规则路径
          cmd_options: '-I -T 180'  # 高级参数：
          # -I: 忽略警告
          # -T: 超时时间(秒)
          # -J: 生成趋势图(需启用后续存储)

      - name: 📈 Store Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results-${{ github.run_id }}
          path: |
            zap_scan.log
            zap-report.*
            trending.png  # 安全趋势图
