name: BaitMate OWASP Security Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐳 Pull OWASP ZAP Docker Image
        run: |
          docker pull owasp/zap2docker-stable || docker pull owasp/zap2docker-weekly

      - name: 🕷️ Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: "http://47.129.5.86:8080"
          fail_action: false
          rules_file_name: ".zap/rules.tsv"

      - name: 📝 Save ZAP Report
        run: mv zap_scan.log $GITHUB_WORKSPACE/zap-report.log

      - name: 📤 Upload ZAP Report (Updated to v4)
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Scan-Report
          path: zap-report.log
