name: BaitMate OWASP Security Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐳 Login to Docker Hub (解决拉取限制)
        if: false  # 实际OWASP镜像无需登录，可跳过此步骤
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🐞 Pull OWASP ZAP Docker Image (使用官方新镜像)
        run: |
          docker pull owasp/zap-stable || docker pull owasp/zap-weekly

      - name: 🕷️ Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: "http://47.129.5.86:8080"
          docker_image: "owasp/zap-stable"  # 明确指定镜像名称
          cmd_options: "-I"  # 忽略扫描错误继续运行
          fail_action: false
          rules_file_name: ".zap/rules.tsv"

      - name: 📤 Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Scan-Report
          path: |
            zap_scan.log
            zap-report.html