name: BaitMate OWASP Security Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐞 Pull OWASP ZAP Docker Image
        run: docker pull owasp/zap-stable

      - name: 🕷️ Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: "http://47.129.5.86:8080"
          cmd_options: "-I -j"  # 忽略警告并生成JSON报告
          fail_action: false
          rules_file_name: ".zap/rules.tsv"

      - name: 📤 Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Scan-Report
          path: |
            zap_scan.log
            zap-report.html
            zap-report.json